# Generated by Django 6.0.1 on 2026-03-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='selo',
            field=models.CharField(blank=True, help_text='Ex: Novo, Promoção, Lançamento, Últimas unidades', max_length=50),
        ),
    ]
