# Generated by Django 6.0.1 on 2026-02-06 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_categoria_produto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoOpcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_opcoes', to='produtos.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Opcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=100)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='produtos.grupoopcao')),
            ],
            options={
                'unique_together': {('grupo', 'valor')},
            },
        ),
    ]
