# Generated by Django 6.0.1 on 2026-03-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_alter_categoria_options_categoria_ordem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='altura',
            field=models.DecimalField(decimal_places=1, default=10, help_text='Altura em cm', max_digits=5),
        ),
        migrations.AddField(
            model_name='produto',
            name='comprimento',
            field=models.DecimalField(decimal_places=1, default=10, help_text='Comprimento em cm', max_digits=5),
        ),
        migrations.AddField(
            model_name='produto',
            name='largura',
            field=models.DecimalField(decimal_places=1, default=10, help_text='Largura em cm', max_digits=5),
        ),
        migrations.AddField(
            model_name='produto',
            name='peso',
            field=models.DecimalField(decimal_places=3, default=0.3, help_text='Peso em kg (ex: 0.300)', max_digits=6),
        ),
    ]
