# Generated by Django 6.0.1 on 2026-02-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_produtoimagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtoimagem',
            name='tipo',
            field=models.CharField(choices=[('hover', 'Imagem de hover'), ('detalhe', 'Imagem de detalhe')], default='detalhe', max_length=10),
        ),
    ]
