# Generated by Django 6.0.1 on 2026-02-11 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_produtoimagem_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produtoimagem',
            options={'ordering': ['ordem'], 'verbose_name': 'Imagem do Produto', 'verbose_name_plural': 'Imagens do Produto'},
        ),
    ]
