# Generated by Django 6.0.1 on 2026-02-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_alter_produtoimagem_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='produtoimagem',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo', 'hover')), fields=('produto', 'tipo'), name='unique_hover_image_por_produto'),
        ),
    ]
