# Generated by Django 6.0.1 on 2026-03-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_avaliacao_imagemsobre'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='avaliacoes/'),
        ),
    ]
