# Generated by Django 6.0.1 on 2026-02-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_produtoimagem_unique_hover_image_por_produto'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='produtoimagem',
            name='unique_hover_image_por_produto',
        ),
        migrations.AddConstraint(
            model_name='produtoimagem',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo', 'hover')), fields=('produto',), name='unique_hover_image_por_produto'),
        ),
    ]
