# Generated by Django 6.0.1 on 2026-03-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_avaliacao_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSobre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_equipe', models.ImageField(blank=True, help_text="Foto da equipe/loja exibida na seção 'Nossa história'", null=True, upload_to='sobre/')),
            ],
            options={
                'verbose_name': 'Configuração da Página Sobre',
                'verbose_name_plural': 'Configuração da Página Sobre',
            },
        ),
    ]
