# Generated by Django 6.0.1 on 2026-02-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_remove_produtoimagem_unique_hover_image_por_produto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='permite_personalizacao',
            field=models.BooleanField(default=False),
        ),
    ]
