# Generated by Django 6.0.1 on 2026-03-20 20:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_configuracaosobre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagemsobre',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Imagem da Página Sobre', 'verbose_name_plural': 'Imagens da Página Sobre'},
        ),
        migrations.AddField(
            model_name='imagemsobre',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
