# Generated by Django 6.0.1 on 2026-03-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_alter_imagemsobre_options_imagemsobre_criado_em'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='categoria',
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.ManyToManyField(blank=True, related_name='produtos', to='produtos.categoria'),
        ),
    ]
