# Generated by Django 6.0.1 on 2026-03-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0009_remove_produto_categoria_produto_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracaosobre',
            options={'verbose_name': 'Imagem da equipe/loja no Sobre', 'verbose_name_plural': 'Imagem da equipe/loja no Sobre'},
        ),
        migrations.AlterModelOptions(
            name='imagemsobre',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Imagem dos prdutos na mão dos clientes na página Sobre', 'verbose_name_plural': 'Imagem dos prdutos na mão dos clientes na página Sobre'},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Cadastrar produtos', 'verbose_name_plural': 'Cadastrar produtos'},
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(upload_to='produtos/'),
        ),
    ]
