# Generated by Django 6.0.1 on 2026-03-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0010_alter_configuracaosobre_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='foto',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='avaliacoes/'),
        ),
        migrations.AlterField(
            model_name='configuracaosobre',
            name='foto_equipe',
            field=models.ImageField(blank=True, help_text="Foto da equipe/loja exibida na seção 'Nossa história'", max_length=500, null=True, upload_to='sobre/'),
        ),
        migrations.AlterField(
            model_name='imagemsobre',
            name='imagem',
            field=models.ImageField(max_length=500, upload_to='sobre/'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(max_length=500, upload_to='produtos/'),
        ),
        migrations.AlterField(
            model_name='produtoimagem',
            name='imagem',
            field=models.ImageField(max_length=500, upload_to='produtos/galeria/'),
        ),
    ]
