# Generated by Django 6.1 on 2026-09-08 15:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0011_alter_avaliacao_foto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagemsobre',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Imagem dos produtos na mão dos clientes na página Sobre', 'verbose_name_plural': 'Imagens dos produtos na mão dos clientes na página Sobre'},
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='foto',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='avaliacoes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='configuracaosobre',
            name='foto_equipe',
            field=models.ImageField(blank=True, help_text="Foto da equipe/loja exibida na seção 'Nossa história'", max_length=500, null=True, upload_to='sobre/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='imagemsobre',
            name='imagem',
            field=models.ImageField(max_length=500, upload_to='sobre/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(max_length=500, upload_to='produtos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='produtoimagem',
            name='imagem',
            field=models.ImageField(max_length=500, upload_to='produtos/galeria/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
