# Generated by Django 6.0.1 on 2026-03-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemcarrinho',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='itemcarrinho',
            name='opcoes',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
