# Generated by Django 6.0.1 on 2026-03-10 16:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='data_criacao',
            new_name='criado_em',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='total_geral',
            new_name='total',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='total_produtos',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='valor_frete',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cep_entrega',
            field=models.CharField(default=0, max_length=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('criado', 'Criado'), ('aguardando_pagamento', 'Aguardando pagamento'), ('pago', 'Pago'), ('em_producao', 'Em produção'), ('cancelado', 'Cancelado'), ('expirado', 'Expirado'), ('enviado', 'Enviado'), ('entregue', 'Entregue')], default='criado', max_length=30),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('pix', 'Pix'), ('cartao', 'Cartão'), ('boleto', 'Boleto')], max_length=20)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado')], default='pendente', max_length=20)),
                ('transaction_id', models.CharField(max_length=200, unique=True)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('qr_code', models.TextField(blank=True)),
                ('qr_code_base64', models.TextField(blank=True)),
                ('boleto_url', models.URLField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pix_expira_em', models.DateTimeField(blank=True, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='pedidos.pedido')),
            ],
        ),
    ]
