# Generated by Django 6.0.1 on 2026-03-10 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_pedido_bairro_pedido_cidade_pedido_complemento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
