# Generated by Django 6.0.1 on 2026-03-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_alter_pagamento_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='boleto_url',
            field=models.TextField(blank=True),
        ),
    ]
