# Generated by Django 6.0.1 on 2026-03-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_alter_pagamento_boleto_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
