# Generated by Django 6.0.3 on 2026-04-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_pedido_nome_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='tipo_entrega',
            field=models.CharField(choices=[('entrega', 'Entrega'), ('retirada', 'Retirada na loja')], default='entrega', max_length=20, verbose_name='Tipo de entrega'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='whatsapp_retirada',
            field=models.CharField(blank=True, max_length=20, verbose_name='WhatsApp para retirada'),
        ),
    ]
